# Generated by Django 4.2.3 on 2023-09-30 14:22

from django.db import migrations, models
import todo_app.tasks.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(validators=[todo_app.tasks.validators.validate_date_is_not_in_the_past]),
        ),
    ]
