# Generated by Django 4.2.3 on 2023-09-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='moved_to_completed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
