# Generated by Django 4.2.3 on 2023-10-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_moved_to_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_of_completion',
            field=models.DateField(null=True),
        ),
    ]
