# Generated by Django 4.2.3 on 2023-08-15 18:49

import django.core.validators
from django.db import migrations, models
import todo_app.accounts.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(4), todo_app.accounts.validators.validate_name_contains_valid_symbols_and_numbers])),
                ('password', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(8), todo_app.accounts.validators.validate_password_is_strong])),
                ('repeated_password', models.CharField(max_length=30)),
            ],
        ),
    ]
