# Generated by Django 4.2.3 on 2023-09-08 16:41

import django.core.validators
from django.db import migrations, models
import todo_app.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8), todo_app.accounts.validators.validate_password_is_strong]),
        ),
        migrations.AlterField(
            model_name='account',
            name='repeated_password',
            field=models.CharField(max_length=128),
        ),
    ]
